import { normalizeZoneFields } from "./zoneTaxonomy";

export type ExtractedUnit = { societyName: string; unitNumber: string; areaSqft: number | null; configuration: string | null; floor: string | null; locality: string | null; marketRegion: string | null; zone: string | null; microZone: string | null; status: string | null; askPriceDisplay: string | null; askPriceValue: number | null; isMarkedNew: boolean };
export const parseIndianPrice = (display: string | null | undefined, numeric?: number | null) => { if (numeric != null && Number.isFinite(Number(numeric))) return Number(numeric); if (!display) return null; const value = Number(display.replace(/,/g, "").match(/[0-9]+(?:\.[0-9]+)?/)?.[0] ?? ""); if (!value) return null; const lower = display.toLowerCase(); return Math.round(value * (lower.includes("cr") ? 10000000 : lower.includes("lac") || lower.includes("lakh") ? 100000 : 1)); };
export const normalizeUnit = (u: ExtractedUnit): ExtractedUnit => ({ ...u, societyName: (u.societyName || "Unknown society").trim(), unitNumber: (u.unitNumber || "").replace(/\s*-\s*/g, "-").replace(/\s+/g, " ").trim(), ...normalizeZoneFields(u), askPriceDisplay: u.askPriceDisplay?.trim() || null, askPriceValue: parseIndianPrice(u.askPriceDisplay, u.askPriceValue) });
export const unitKey = (u: Pick<ExtractedUnit, "societyName" | "unitNumber">) => `${u.societyName}::${u.unitNumber}`.toLowerCase();
export const completenessScore = (units: ExtractedUnit[]) => { const required = ["unitNumber", "societyName", "configuration", "floor", "status", "areaSqft", "askPriceValue"]; const total = Math.max(units.length * required.length, 1); const present = units.reduce((n, u) => n + required.filter(k => u[k as keyof ExtractedUnit] !== null && u[k as keyof ExtractedUnit] !== undefined && u[k as keyof ExtractedUnit] !== "").length, 0); return Math.round((present / total) * 100); };
export const mergeExtractedUnits = (groups: ExtractedUnit[][]) => Array.from(new Map(groups.flat().map(normalizeUnit).filter(u => u.unitNumber).map(u => [unitKey(u), u])).values());
export const incompleteUploadWarning = (previousCount: number, todayCount: number, score: number) => { const missing = Math.max(previousCount - todayCount, 0); if (previousCount > 0 && missing > Math.max(10, Math.round(previousCount * 0.35))) return `Today's upload may be incomplete. ${missing} units are missing from the previous confirmed inventory.`; if (score < 72) return "Some extracted rows are missing required fields. Review before confirming."; return null; };
export const compareUnits = (today: ExtractedUnit[], yesterday: any[]) => { const previous = new Map(yesterday.map(u => [u.unitKey, u])); const current = new Map(today.map(u => [unitKey(u), u])); const changes: Array<{ type: "sourced" | "existing" | "updated" | "price_changed" | "potentially_sold"; unit: ExtractedUnit | any; before?: any }> = []; current.forEach((unit, key) => { const before = previous.get(key); if (!before) changes.push({ type: "sourced", unit }); else if (String(before.askPriceValue ?? "") !== String(unit.askPriceValue ?? "")) changes.push({ type: "price_changed", unit, before }); else if (before.status !== unit.status || before.areaSqft !== unit.areaSqft || before.configuration !== unit.configuration) changes.push({ type: "updated", unit, before }); else changes.push({ type: "existing", unit, before }); }); previous.forEach((unit, key) => { if (!current.has(key)) changes.push({ type: "potentially_sold", unit }); }); return changes; };
